### ISSUE TITLE
月をまとめて作れると、嬉しいのかも？

### ISSUE THREAD

**Issue by yusuke0701** [komem3/go-diary#10]
まとめて作っておいて、予定をかけると嬉しいのかもしれないと思いましたー

**Comment by komem3** [comment]
@yusuke0701 
その機能を作るなら、特定の日付のファイルに飛べたほうが便利ですね。
それか、index となるファイルをもう少し見やすいように工夫するとか？

**Comment by komem3** [comment]
僕にやる気がないのでクローズします。
